src/Entity/ProduitTroc.php
<?php

namespace App\Entity;

use App\Repository\ProduitTrocRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProduitTrocRepository::class)]
class ProduitTroc
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "You should insert the name of your product")]
    #[Assert\Length(min: 3, minMessage: "the name should at least have 3 caracter")]

    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:  "You should insert the category of your product")]

    private ?string $category = null;

    #[ORM\Column(length: 1000)]
    #[Assert\NotBlank(message:  "You should insert the description of your product")]
    #[Assert\Length(min: 7, minMessage: "La description doit contenir au moins 5 caractères.")]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]

    private ?int $statut = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;


    #[ORM\ManyToOne(inversedBy: 'produitTrocs')]

    private ?User $id_user = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:  "You should insert the product your serching for ")]
    #[Assert\Length(min: 5, minMessage: "name have to ta lest have 5 caracter")]
    private ?string $nom_produit_recherche = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString(): string
    {
        return $this->getId();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(?int $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getNomProduitRecherche(): ?string
    {
        return $this->nom_produit_recherche;
    }

    public function setNomProduitRecherche(string $nom_produit_recherche): static
    {
        $this->nom_produit_recherche = $nom_produit_recherche;

        return $this;
    }
}

src/Controller/ProduitTrocController.php
<?php

namespace App\Controller;
use App\Entity\ProduitTrocWith;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\ProduitTroc ;
use App\Form\ProduitTroc1Type;
use App\Repository\ProduitTrocRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;
use Twilio\Rest\Client;

use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\HttpFoundation\JsonResponse;



#[Route('/produit/troc')]
class ProduitTrocController extends AbstractController
{
    private const API_URL = 'https://api.openai.com/v1/engines/text-davinci-003/completions';
    private const API_KEY = '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';
    #[Route('/', name: 'app_produit_troc_index', methods: ['GET'])]
    public function index(ProduitTrocRepository $produitTrocRepository): Response
    {
        return $this->render('index1.html.twig', [
            'produit_trocs' => $produitTrocRepository->findAllExceptStatusZero(),
        ]);
    }

    #[Route('/PRS/{id}', name: 'change_status', methods: ['GET'])]
    public function changeStatus(int $id, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }

        $produitTroc = $entityManager->getRepository(ProduitTroc::class)->find($id);

        if (!$produitTroc) {
            throw $this->createNotFoundException('Produit Troc not found');
        }

        // Change status from 0 to 1
        $produitTroc->setStatut(1);

        $entityManager->flush();
        $this->addFlash('success', 'the product is verified ');

        // Redirect back to the index page
        return $this->redirectToRoute('app_produit_troc_index_back');
    }

    #[Route('/m', name: 'app_produit_troc_mine', methods: ['GET'])]
    public function indexmi(ProduitTrocRepository $produitTrocRepository): Response
    {
        $user = $this->getUser();
        // Vérifier si l'utilisateur est authentifié
        if ($user) {
            // Récupérer les dons de l'utilisateur authentifié
            $don_bien_materiels = $produitTrocRepository->findBy(['id_user' => $user]);
        } else {
            // Gérer le cas où aucun utilisateur n'est authentifié
            // Par exemple, rediriger vers la page de connexion
            return $this->redirectToRoute('app_login');
        }

        return $this->render('index1.html.twig', [
            'produit_trocs' => $don_bien_materiels,
        ]);
        
    }
    #[Route('/search', name: 'app_produit_troc_search', methods: ['POST'])]

// Inside your controller action method




#[Route('/chat', name: 'app_chat_index')]
public function index11(Request $request): Response
{
    $user = $this->getUser();
    if (!$user) {
        throw $this->createNotFoundException('User not found');
    }
    $question = $request->query->get('question');

    if ($question) {
        try {
            // Get the answer from the API
            $answer = $this->getAnswerFromAPI($question);
            return $this->render('chatgbt.html.twig', [
                'answer' => $answer,
            ]);
        } catch (\Exception $e) {
            // Handle API request errors
            return $this->render('chatgbt.html.twig', [
                'answer' => 'I\'m sorry, I can only answer questions related to JardinDars products and services Please try again.',
            ]);
        }
    }

    // No question provided, render the chat page with default message
    return $this->render('chatgbt.html.twig', [
        'answer' => 'I\'m sorry, I can only answer questions related to JardinDars products and services.',
    ]);
}

    // #[Route('/b', name: 'app_produit_troc_index_back', methods: ['GET'])]
    // public function indexback(ProduitTrocRepository $produitTrocRepository): Response
    // {
    //     return $this->render('prod_troc.html.twig', [
    //         'produit_trocs' => $produitTrocRepository->findAll(),
    //     ]);
    // }
    #[Route('/l', name: 'app_produit_troc_indexES', methods: ['GET'])]
    public function indexEd(ProduitTrocRepository $produitTrocRepository): Response
    {
        return $this->render('indexES.html.twig', [
            'produit_trocs' => $produitTrocRepository->findAll(),
        ]);
    }

    #[Route('/b', name: 'app_produit_troc_index_back', methods: ['GET'])]
    public function indexback(ProduitTrocRepository $produitTrocRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $user = $this->getUser();
        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }
        $produitTrocQuery = $produitTrocRepository->findAll(); // Fetch all records
    
        // Paginate the results
        $produitTroc = $paginator->paginate(
            $produitTrocQuery, // Doctrine Query, not results
            $request->query->getInt('page', 1), // Current page number, defaults to 1
            5 // Number of items per page
        );
    
        return $this->render('prod_troc.html.twig', [
            'produit_trocs' => $produitTroc,
            'pagination' => $produitTroc // Pass the paginated results to the template
        ]);
    }

    #[Route('/new', name: 'app_produit_troc_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        $user = $this->getUser();
        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }
        $produitTroc = new ProduitTroc();
        $form = $this->createForm(ProduitTroc1Type::class, $produitTroc);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();
    
            if ($imageFile) {
                $newFilename = uniqid().'.'.$imageFile->guessExtension();
    
                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'), // Destination directory, should be defined in the configuration file
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle the exception, such as logging an error message or displaying a user-friendly error
                    echo 'An error occurred: ' . $e->getMessage();
                    // You might want to return an error response here
                }
    
                $produitTroc->setImage($newFilename);
                $produitTroc->setStatut(0); // Use setStatut instead of getStatut
                $produitTroc->setIdUser($user);
            }
    
            $entityManager->persist($produitTroc);
            $entityManager->flush();
    
            // Initialize Twilio client
             $sid = "ACbd337248e7718753c1a2a9b2b882db86";
             $token = "42c577ae5a2444294a2d7e1d761d32ca";
             $receiverPhoneNumber = $produitTroc->getIdUser()->getTel(); // Assuming you have appropriate methods in your entities

             $res = '+21650852180' ; // Concatenate the country code with the telephone number
             $twilio = new Client($sid, $token);
         var_dump($res);

             // Send SMS to the user
        $message = $twilio->messages
                 ->create(
                   $res, // User's phone number
                    [
                       "from" => "+14437753032", // Your Twilio phone number
                      "body" => "Hi  Your product  for exchange has been added successfully wait for the admin approval."
                    ]
                );
    
            return $this->redirectToRoute('app_produit_troc_index', [], Response::HTTP_SEE_OTHER);
        }
    

        return $this->renderForm('produit_troc/new1.html.twig', [
            'produit_troc' => $produitTroc,
            'form' => $form,
        ]);
    }
    
    


    #[Route('/{idprd}', name: 'app_produit_troc_show', methods: ['GET'])]
    public function show_troc($idprd,ProduitTrocRepository $repository): Response
    {
            $produitTroc = $repository->find($idprd);
            return $this->render('produit_troc/show.html.twig', [
            'produit_troc' => $produitTroc,
        ]);
    }


    #[Route('/edit/{id}', name: 'app_produit_troc_edit', methods: ['GET', 'POST'])]
    public function edit($id, ?int $idUser = null, Request $request, ProduitTroc $produitTroc, EntityManagerInterface $entityManager, ProduitTrocRepository $repository): Response
    {
        // Fetch the ProduitTroc entity by its ID
        $produitTroc = $repository->find($id);
        if (!$produitTroc) {
            throw $this->createNotFoundException('ProduitTroc not found');
        }
    
        $form = $this->createForm(ProduitTroc1Type::class, $produitTroc);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile|null $imageFile */
            $imageFile = $form->get('image')->getData();
    
            // Debugging: Dump the image file data
            dump($imageFile);
    
            // Check if a new image was uploaded
            if ($imageFile) {
                $newFilename = uniqid().'.'.$imageFile->guessExtension();
    
                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {

templates/produit_troc/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_troc_delete', {'id': produit_troc.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit_troc.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit_troc/edit.html.twig
{% extends 'HomeOn.html.twig' %}

{% block titleED %}<title>Edit ProduitTroc</title>{% endblock %}

{% block body %}
<section class="login py-5 border-top-1">
    <div class="container">
        <div class="border border">
            <h1 class="bg-gray p-4">Edit your Product</h1>
            <form method="post" action="{{ path('app_produit_troc_edit', {'id': form.vars.data.id}) }}">
                {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

                {{ form_row(form.nom, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                {{ form_errors(form.nom) }}

                {{ form_row(form.description, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                {{ form_errors(form.description) }}

                {{ form_row(form.category, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                {{ form_errors(form.category) }}

                <br>

                {{ form_row(form.nom_produit_recherche, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                {{ form_errors(form.nom_produit_recherche) }}

                {{ form_row(form.image, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                {{ form_errors(form.image) }}

                {{ form_row(form.save, {
                    'label': 'Edit',
                    'attr': {
                        'class': 'btn btn-primary font-weight-bold mt-3',
                        'type': 'submit'
                    }
                }) }}
                
                {{ form_end(form) }}
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/produit_troc/edit1.html.twig
{% extends 'HomeOn.html.twig' %}

{% block titreprod %}<title>New ProduitTroc</title>{% endblock %}

{% block body %}
<body class="body-wrapper">
    <section class="advt-post bg-gray py-5">
        <div class="container">
            {# <form method="post" action="{% if produit_troc is defined %}
    {{ path('app_produit_troc_edit', {'idprd': produit_troc.id}) }}
                        {% else %}
                            {{ path('/') }}
                        {% endif %}"> #}
                        <form method="post" action="{% if produit_troc is defined %}
{{ path('app_produit_troc_edit', {'id': produit_troc.id}) }}
{% else %}
    {{ path('app_produit_troc_edit', {'idprd': idprd}) }}
{% endif %}">

                {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

                <!-- Post Your ad start -->
                <fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
                    <div class="row">
                        <div class="col-lg-12">
                            <h3>Edit Your Echange</h3>
                        </div>
                        <div class="col-lg-6">
                            {{ form_row(form.nom, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                            {{ form_errors(form.nom) }}

                            {{ form_row(form.description, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
                            {{ form_errors(form.description) }}
                        </div>
                        <div class="col-lg-6">
                            {{ form_row(form.category, {'attr': {'class': 'form-control'}}) }}
                            {{ form_errors(form.category) }}

                            {{ form_row(form.nom_produit_recherche, {'attr': {'class': 'form-control'} }) }}
                            {{ form_errors(form.nom_produit_recherche) }}

                            {{ form_row(form.statut, {'attr': {'style': 'display: none;'}}) }}

                            <div class="choose-file text-center my-4 py-4 rounded bg-white">
                                <label for="file-upload">
                                    <span class="d-block font-weight-bold text-dark">Drop files anywhere to upload</span>
                                    <span class="d-block">or</span>
                                    <span class="d-block btn bg-primary text-white my-3 select-files">Select files</span>
                                    <span class="d-block">Maximum upload file size: 500 KB</span>
                                    {{ form_row(form.image, {'attr': {'class': 'form-control-file d-none'}, 'help_attr': {'style': 'color: red;'}, 'label_attr': {'class': 'd-none'}, 'id': 'file-upload'}) }}
                                </label>
                            </div>
                        </div>
                    </div>

                    <!-- Checkbox for terms and conditions -->
                    <div class="checkbox d-inline-flex">
                        <input type="checkbox" id="terms-and-conditions" name="terms_and_conditions" class="mt-1" required>
                        <label for="terms-and-conditions" class="ml-2">By clicking, you must agree with our
                            <span><a class="text-success" href="terms-condition.html">Terms & Condition and Posting Rules.</a></span>
                        </label>
                    </div>

                    <!-- Submit buttons -->
{{ form_row(form.save, {'label': 'Update', 'attr': {'class': 'btn btn-primary font-weight-bold mt-3', 'type': 'submit'}}) }}                </fieldset>

                {{ form_end(form) }}
            </form>
        </div>
    </section>
</body>
{% endblock %}

templates/produit_troc/index.html.twig
{% extends 'HomeOn.html.twig' %}

{% block titreprod %}<title>ProduitTroc index</title>{% endblock %}

{% block body %}
    <h1>ProduitTroc index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Category</th>
                <th>Description</th>
                <th>Statut</th>
                <th>Image</th>
                <th>Nom_produit_recherche</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit_troc in produit_trocs %}
            <tr>
                <td>{{ produit_troc.id }}</td>
                <td>{{ produit_troc.nom }}</td>
                <td>{{ produit_troc.category }}</td>
                <td>{{ produit_troc.description }}</td>
<td>
    {% if produit_troc.statut == 0 %}
        Not Checked
    {% else %}
        Checked
    {% endif %}
</td>         <td>     {% if produit_troc.image %}
    <img src="{{ asset('/uploads/images/' ~ produit_troc.image) }}" alt="Product Image">
{% else %}

    <p>No image available</p>
{% endif %}</td>
                <td>{{ produit_troc.nomProduitRecherche }}</td>
                <td>
                    <a href="{{ path('app_produit_troc_show', {'idprd': produit_troc.getId()}) }}">show</a>
                    <a href="{{ path('app_produit_troc_edit', {'id': produit_troc.id}) }}">edit</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<a href="{{ path('app_produit_troc_new') }}" class="btn btn-primary">Create New</a>

{% endblock %}

templates/produit_troc/index1.html.twig
{% extends 'HomeOn.html.twig' %}

{% block titreprod %}
    <title>ProduitTroc index</title>
{% endblock %}

{% block body %}
    <!--==================================
    =            User Profile            =
    ===================================-->
    <section class="dashboard section">
        <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
              
                <div class="col-lg-8">
                    <!-- Recently Favorited -->
                    <div class="widget dashboard-container my-adslist">
                        <h3 class="widget-header">All the product available for exchange </h3>
                        <table class="table table-responsive product-dashboard-table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Title</th>
                                    <th class="text-center">Category</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Loop through your product_trocs here -->
                                {% for produit_troc in produit_trocs %}
                                    <tr>
                                        <!-- Include the content for each product_troc here -->
                                        <td>
                                            {% if produit_troc.image %}
                                                <img width="80px" height="auto" src="{{ asset('/uploads/images/' ~ produit_troc.image) }}" alt="Product Image">
                                            {% else %}
                                                <p>No image available</p>
                                            {% endif %}
                                        </td>
                                       
                                        <td class="product-category"><span class="categories">{{ produit_troc.category }}</span></td>
                                        <td class="action" data-title="Action">
                                            <div class="">
                                                <ul class="list-inline justify-content-center">
                                                    <li class="list-inline-item">
                                                        <a data-toggle="tooltip" data-placement="top" title="View" class="view" href="{{ path('app_produit_troc_show', {'id': produit_troc.id}) }}">
                                                            <i class="fa fa-eye"></i>
                                                        </a>
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <a data-toggle="tooltip" data-placement="top" title="Edit" class="edit" href="{{ path('app_produit_troc_edit', {'id': produit_troc.id}) }}">
                                                            <i class="fa fa-pencil"></i>
                                                        </a>
                                                    </li>
                                                    <li class="list-inline-item">
    <a data-toggle="tooltip" data-placement="top" title="Exchange" class="edit" href="{{ path('app_produit_troc_edit', {'id': produit_troc.id}) }}">
        <div class="logo-container">
            <i class="fa fa-pencil overlay-icon"></i>
        </div>
    </a>
</li>

                                                    <!-- Add delete functionality if needed -->
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="8">no records found</td>
                                    </tr>
                                {% endfor %}
                                <!-- End of loop -->
                            </tbody>
                        </table>
                    </div>
                    <!-- pagination -->
                    <!-- Include pagination if needed -->
                    <!-- pagination -->
                </div>
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </section>
{% endblock %}

templates/produit_troc/new.html.twig
{% extends 'HomeOn.html.twig' %}



{% block titreprod %}<title>New ProduitTroc</title> {% endblock %}

{% block body %}
<section class="login py-5 border-top-1">
        <div class="container">
        <div class="border border">
    <h1 class="bg-gray p-4">Submit your exchange</h1>
   
          <form method="post" action="{{ path('app_produit_troc_new') }}" enctype="multipart/form-data">
    {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
 
   {{ form_row(form.nom, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
          {{ form_errors(form.nom) }}



        {{ form_row(form.description, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
        {{ form_errors(form.description) }}

        {{ form_row(form.category, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
        {{ form_errors(form.category) }}
<br>
        {{ form_row(form.nom_produit_recherche, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}}) }}
        {{ form_errors(form.nom_produit_recherche) }}

        {{ form_row(form.image, {'attr': {'class': 'form-control'}, 'help_attr': {'style': 'color: red;'}})}}
        {{ form_errors(form.image) }}
          
 {# {{ form_row(form.id_user, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.id_user) }} #}
      
       {{ form_row(form.save, {
    'label': 'Save',
    'attr': {
        'class': 'btn btn-primary font-weight-bold mt-3',
        'type': 'submit'
    }
}) }}

    </fieldset>
    {{ form_end(form) }}

</form>
</div>
      </div>
      </section>  

{% endblock %}

templates/produit_troc/show.html.twig
{% extends 'HomeOn.html.twig' %}

{% block titreprod %}<title>ProduitTroc</title>{% endblock %}

{% block body %}
    <h1>ProduitTroc</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit_troc.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ produit_troc.nom }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ produit_troc.category }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit_troc.description }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ produit_troc.statut == 0 ? 'Not Checked' : 'Checked' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>
                    {% if produit_troc.image %}
                        <img width="80px" height="auto" src="{{ asset('/uploads/images/' ~ produit_troc.image) }}" alt="Product Image">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Product searched for</th>
                <td>{{ produit_troc.nomProduitRecherche }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_produit_troc_index') }}" class="btn btn-link">Back to List</a>
    <a  href="{{ path('app_produit_troc_edit', {'id': produit_troc.id}) }}" class="btn btn-link">Edit</a> 

    <form method="post" action="{{ path('app_produit_troc_delete', {'id': produit_troc.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit_troc.id) }}">
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}