src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 500)]
    private ?string $contenu_blog = null;

    #[ORM\Column]
    private ?int $status = null;

    #[ORM\Column(nullable: true)]
    private ?int $rate = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'blog', targetEntity: ReponseBlog::class)]
    private Collection $reponseBlogs;

    public function __construct()
    {
        $this->reponseBlogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenuBlog(): ?string
    {
        return $this->contenu_blog;
    }

    public function setContenuBlog(string $contenu_blog): static
    {
        $this->contenu_blog = $contenu_blog;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(?int $rate): static
    {
        $this->rate = $rate;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, ReponseBlog>
     */
    public function getReponseBlogs(): Collection
    {
        return $this->reponseBlogs;
    }

    public function addReponseBlog(ReponseBlog $reponseBlog): static
    {
        if (!$this->reponseBlogs->contains($reponseBlog)) {
            $this->reponseBlogs->add($reponseBlog);
            $reponseBlog->setBlog($this);
        }

        return $this;
    }

    public function removeReponseBlog(ReponseBlog $reponseBlog): static
    {
        if ($this->reponseBlogs->removeElement($reponseBlog)) {
            // set the owning side to null (unless already changed)
            if ($reponseBlog->getBlog() === $this) {
                $reponseBlog->setBlog(null);
            }
        }

        return $this;
    }
}

src/Controller/BackBlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Form\Blog1Type;
use App\Repository\BlogRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/back/blog')]
class BackBlogController extends AbstractController
{
    #[Route('/', name: 'app_back_blog_index', methods: ['GET'])]
    public function index(BlogRepository $blogRepository): Response
    {
        return $this->render('back_blog/index.html.twig', [
            'blogs' => $blogRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_back_blog_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $blog = new Blog();
        $form = $this->createForm(Blog1Type::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($blog);
            $entityManager->flush();

            return $this->redirectToRoute('app_back_blog_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back_blog/new.html.twig', [
            'blog' => $blog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_back_blog_show', methods: ['GET'])]
    public function show(Blog $blog): Response
    {
        return $this->render('back_blog/show.html.twig', [
            'blog' => $blog,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_back_blog_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Blog $blog, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Blog1Type::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_back_blog_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back_blog/edit.html.twig', [
            'blog' => $blog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_back_blog_delete', methods: ['POST'])]
    public function delete(Request $request, Blog $blog, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$blog->getId(), $request->request->get('_token'))) {
            $entityManager->remove($blog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_back_blog_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back_blog/_delete_form.html.twig
<form method="post" action="{{ path('app_back_blog_delete', {'id': blog.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blog.id) }}">
    <button class="btn">Delete</button>
</form>

templates/back_blog/edit.html.twig
{% extends 'back.html.twig' %}

{% block titre %}<title>Edit Blog</title>{% endblock %}


{% block body %}
<section class="advt-post bg-gray py-5">
  <div class="container">
    <form action="#!" method="POST">
      <!-- Post Your ad start -->
      <fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
        <div class="row">
          <div class="col-lg-12">
<body class="body-wrapper">
    <section class="advt-post bg-gray py-5">
        <div class="container">
            <form method="post" action="{{ path('app_back_blog_edit') }}" enctype="multipart/form-data">
                {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

                <!-- Post Your ad start -->
                <fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
                    <div class="row">
                        <div class="col-lg-12">
                            <h3>Post  blog</h3>
                        </div>
                        <div class="col-lg-6">
                              <h6 class="font-weight-bold pt-4 pb-1">
                             
</h6>

                          
                        </div>
                        <div>
                         
                            
 
                   
                        </div>
                        </div>
                       

                        
 <!-- Post Your ad end -->

                <!-- Checkbox for terms and conditions -->
               {{ form_label(form.titre) }}
{{ form_widget(form.titre, {'attr': {'class': 'form-control bg-whitel', 'placeholder': 'Ad title goes here'}, 'help_attr': {'style': 'color: red;'}}) }}
                    {{ form_errors(form.titre) }}
                    {{ form_label(form.category) }}
                         {{ form_widget(form.category, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.category) }}
   {{ form_label(form.rate) }}
{{ form_widget(form.rate, {'attr': {'class': 'form-control'} }) }}
                    {{ form_errors(form.rate) }}
                     {{ form_label(form.status) }}
                     {{ form_widget(form.status, {'attr': {'class': 'form-control'} }) }}
                    {{ form_errors(form.status) }}
                      {{ form_label(form.contenu_blog) }}
                     {{ form_widget(form.contenu_blog, {'attr': {'class': 'form-control'} }) }}
                    {{ form_errors(form.contenu_blog) }}


                <!-- Submit buttons -->
               <button type="submit" class="btn btn-primary"> save </button>
                    </div>
            

                </fieldset>
                               </fieldset>

                
                {{ form_end(form) }}
            </form>
        </div>
                </div>
        </div>

                                </div>
 </form>
    </section>
        </section>

</body>
{% endblock %}

templates/back_blog/index.html.twig
{% extends 'back.html.twig' %}

<title>Blog index</title>

{% block body %}
    <h1>Blog index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Category</th>
                <th>Titre</th>
                <th>Contenu_blog</th>
                <th>Status</th>
                <th>Rate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for blog in blogs %}
            <tr>
                <td>{{ blog.id }}</td>
                <td>{{ blog.category }}</td>
                <td>{{ blog.titre }}</td>
                <td>{{ blog.contenuBlog }}</td>
                <td>{{ blog.status }}</td>
                <td>{{ blog.rate }}</td>
                <td>
                    <a href="{{ path('app_back_blog_show', {'id': blog.id}) }}">show</a>
                    <a href="{{ path('app_back_blog_edit', {'id': blog.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_back_blog_new') }}">Create new</a>
{% endblock %}

templates/back_blog/new.html.twig
{% extends 'back.html.twig' %}

{% block titre %}<title>New Blog</title>{% endblock %}


{% block body %}
<section class="advt-post bg-gray py-5">
  <div class="container">
    <form action="#!" method="POST">
      <!-- Post Your ad start -->
      <fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
        <div class="row">
          <div class="col-lg-12">
<body class="body-wrapper">
    <section class="advt-post bg-gray py-5">
        <div class="container">
            <form method="post" action="{{ path('app_back_blog_new') }}" enctype="multipart/form-data">
                {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

                <!-- Post Your ad start -->
                <fieldset class="border border-gary px-3 px-md-4 py-4 mb-5">
                    <div class="row">
                        <div class="col-lg-12">
                            <h3>Post  blog</h3>
                        </div>
                        <div class="col-lg-6">
                              <h6 class="font-weight-bold pt-4 pb-1">
                             
</h6>

                          
                        </div>
                        <div>
                         
                            
 
                   
                        </div>
                        </div>
                       

                        
 <!-- Post Your ad end -->

                <!-- Checkbox for terms and conditions -->
               {{ form_label(form.titre) }}
{{ form_widget(form.titre, {'attr': {'class': 'form-control bg-whitel', 'placeholder': 'Ad title goes here'}, 'help_attr': {'style': 'color: red;'}}) }}
                    {{ form_errors(form.titre) }}
                    {{ form_label(form.category) }}
                         {{ form_widget(form.category, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.category) }}
   {{ form_label(form.rate) }}
{{ form_widget(form.rate, {'attr': {'class': 'form-control'} }) }}
                    {{ form_errors(form.rate) }}
                     {{ form_label(form.status) }}
                     {{ form_widget(form.status, {'attr': {'class': 'form-control'} }) }}
                    {{ form_errors(form.status) }}
                      {{ form_label(form.contenu_blog) }}
                     {{ form_widget(form.contenu_blog, {'attr': {'class': 'form-control'} }) }}
                    {{ form_errors(form.contenu_blog) }}


                <!-- Submit buttons -->
               <button type="submit" class="btn btn-primary"> save </button>
                    </div>
            

                </fieldset>
                               </fieldset>

                
                {{ form_end(form) }}
            </form>
        </div>
                </div>
        </div>

                                </div>
 </form>
    </section>
        </section>

</body>
{% endblock %}

templates/back_blog/show.html.twig
{% extends 'back.html.twig' %}

<title>Blog</title>

{% block body %}
    <h1>Blog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ blog.id }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ blog.category }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ blog.titre }}</td>
            </tr>
            <tr>
                <th>Contenu_blog</th>
                <td>{{ blog.contenuBlog }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ blog.status }}</td>
            </tr>
            <tr>
                <th>Rate</th>
                <td>{{ blog.rate }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_back_blog_index') }}">back to list</a>

    <a href="{{ path('app_back_blog_edit', {'id': blog.id}) }}">edit</a>

    {{ include('back_blog/_delete_form.html.twig') }}
{% endblock %}