src/Entity/ReponseBlog.php
<?php

namespace App\Entity;

use App\Repository\ReponseBlogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReponseBlogRepository::class)]
class ReponseBlog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?int $nb_likes = null;

    #[ORM\ManyToOne(inversedBy: 'reponseBlogs')]
    private ?Blog $blog = null;

    #[ORM\ManyToOne(inversedBy: 'reponseBlogs')]
    private ?User $id_user_reponse = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): static
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getNbLikes(): ?int
    {
        return $this->nb_likes;
    }

    public function setNbLikes(int $nb_likes): static
    {
        $this->nb_likes = $nb_likes;

        return $this;
    }

    public function getBlog(): ?Blog
    {
        return $this->blog;
    }

    public function setBlog(?Blog $blog): static
    {
        $this->blog = $blog;

        return $this;
    }

    public function getIdUserReponse(): ?User
    {
        return $this->id_user_reponse;
    }

    public function setIdUserReponse(?User $id_user_reponse): static
    {
        $this->id_user_reponse = $id_user_reponse;

        return $this;
    }
}

src/Form/ReponseBlogType.php
<?php

namespace App\Form;

use App\Entity\ReponseBlog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class ReponseBlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('contenu', TextType::class,[
                'required' => false,
                'constraints' => [
                    new NotBlank([
                        'message' => 'La description ne peut pas être vide',
                    ]),
                ],
            ])
            ->add('date')
            ->add('nb_likes')
            ->add('blog')
            ->add('id_user_reponse')
            ->add('save',SubmitType::class,[
                'label'=>'Save',
                'attr'=> ['class'=> 'btn btn-primary mt-3']
              ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ReponseBlog::class,
        ]);
    }
}

src/Controller/ReponseBlogController.php
<?php

namespace App\Controller;

use App\Entity\ReponseBlog;
use App\Form\ReponseBlogType;
use App\Repository\ReponseBlogRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reponse/blog')]
class ReponseBlogController extends AbstractController
{
    #[Route('/', name: 'app_reponse_blog_index', methods: ['GET'])]
    public function index(ReponseBlogRepository $reponseBlogRepository): Response
    {
        return $this->render('reponse_blog/index.html.twig', [
            'reponse_blogs' => $reponseBlogRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reponse_blog_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reponseBlog = new ReponseBlog();
        $form = $this->createForm(ReponseBlogType::class, $reponseBlog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reponseBlog);
            $entityManager->flush();

            return $this->redirectToRoute('app_reponse_blog_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponse_blog/new.html.twig', [
            'reponse_blog' => $reponseBlog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponse_blog_show', methods: ['GET'])]
    public function show(ReponseBlog $reponseBlog): Response
    {
        return $this->render('reponse_blog/show.html.twig', [
            'reponse_blog' => $reponseBlog,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reponse_blog_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ReponseBlog $reponseBlog, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReponseBlogType::class, $reponseBlog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reponse_blog_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponse_blog/edit.html.twig', [
            'reponse_blog' => $reponseBlog,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponse_blog_delete', methods: ['POST'])]
    public function delete(Request $request, ReponseBlog $reponseBlog, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reponseBlog->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reponseBlog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reponse_blog_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reponse_blog/_delete_form.html.twig
<form method="post" action="{{ path('app_reponse_blog_delete', {'id': reponse_blog.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse_blog.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reponse_blog/edit.html.twig
{% extends 'HomeOn.html.twig' %}

{% block body %}
  <h1 style="text-align: center;">Editer votre réponse</h1>
  <div class="form-add">
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    
    <div class="form-group">
      {{ form_label(form.contenu, "Contenu", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.contenu) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.contenu) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.date, "Date", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.date) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.date) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.nb_likes, "Nombre de Likes", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.nb_likes, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.nb_likes) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.nb_likes) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.blog, "Blog", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.blog, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.blog) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.blog) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.id_user_reponse, "ID utilisateur réponse", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.id_user_reponse, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.id_user_reponse) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.id_user_reponse) }}
        </div>
      {% endif %}
    </div>
    
    <div style="padding-top: 10px;"></div>
    <div class="form-group">
      {{ form_row(form.save, {
        'label': 'Save',
        'attr': {
          'class': 'btn btn-primary font-weight-bold mt-3',
          'type': 'submit'
        }
      }) }}
    </div>
    
    {{ form_end(form) }}
  </div>
{% endblock %}

templates/reponse_blog/index.html.twig
{% extends 'HomeOn.html.twig' %}

{% block body %}

    <h1>ReponseBlog index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Contenu</th>
                <th>Date</th>
                <th>Nb_likes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse_blog in reponse_blogs %}
            <tr>
                <td>{{ reponse_blog.id }}</td>
                <td>{{ reponse_blog.contenu }}</td>
                <td>{{ reponse_blog.date ? reponse_blog.date|date('Y-m-d') : '' }}</td>
                <td>{{ reponse_blog.nbLikes }}</td>
                <td>
                
<a href="{{ path('app_reponse_blog_show', {'id': reponse_blog.id}) }}" class="btn btn-primary">Show</a>
                    <a href="{{ path('app_reponse_blog_edit', {'id': reponse_blog.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

<a href="{{ path('app_reponse_blog_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/reponse_blog/new.html.twig
{% extends 'HomeOn.html.twig' %}

{% block body %}
  <h1 style="text-align: center;">Ajouter une réponse</h1>
  <div class="form-add">
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    
    <div class="form-group">
      {{ form_label(form.contenu, "Contenu", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.contenu) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.contenu) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.date, "Date", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.date) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.date) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.nb_likes, "Nombre de Likes", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.nb_likes, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.nb_likes) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.nb_likes) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.blog, "Blog", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.blog, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.blog) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.blog) }}
        </div>
      {% endif %}
    </div>
    
    <div class="form-group">
      {{ form_label(form.id_user_reponse, "ID utilisateur réponse", {'label_attr': {'class': 'form-label'}}) }}
      {{ form_widget(form.id_user_reponse, {'attr': {'class': 'form-control'}}) }}
      {% if form_errors(form.id_user_reponse) %}
        <div class="alert alert-danger mt-2 mb-0" role="alert">
          {{ form_errors(form.id_user_reponse) }}
        </div>
      {% endif %}
    </div>
    
    <div style="padding-top: 10px;"></div>
    <div class="form-group">
      {{ form_row(form.save, {
        'label': 'Save',
        'attr': {
          'class': 'btn btn-primary font-weight-bold mt-3',
          'type': 'submit'
        }
      }) }}
    </div>
    
    {{ form_end(form) }}
  </div>
{% endblock %}

templates/reponse_blog/show.html.twig
{% extends 'HomeOn.html.twig' %}
{% block body %}

<title>ReponseBlog</title>

    <h1>ReponseBlog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse_blog.id }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ reponse_blog.contenu }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reponse_blog.date ? reponse_blog.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nb_likes</th>
                <td>{{ reponse_blog.nbLikes }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reponse_blog_index') }}">back to list</a>

    <a href="{{ path('app_reponse_blog_edit', {'id': reponse_blog.id}) }}">edit</a>

    {{ include('reponse_blog/_delete_form.html.twig') }}
{% endblock %}